### ISSUE TITLE
Question about URL creation

### ISSUE THREAD

**Issue by Malavos** [dgilling/BranchNet#1]
Hi There!

So, I wanna create an url to test out branch.io.
I am right now creating a small object for simple testing:

```
  #region UrlDataParameters
        UrlDataParameters urlDataParameters = new UrlDataParameters();
        urlDataParameters.DesktopUrl = "www.salaonamao.com.br";
        urlDataParameters.WindowsPhoneUrl = "www.salaonamao.com.br";
        urlDataParameters.OgDescription = "testbug OgDescription";
        urlDataParameters.OgTitle = "testbug OgTitle";
  #endregion

  #region UrlParameters<UrlDataParameters>
        UrlParameters<UrlDataParameters> myUrlParameters = new UrlParameters<UrlDataParameters>();
        myUrlParameters.Alias = "testbugUrlDataParametersAlias";
        myUrlParameters.Campaign = "register";
        myUrlParameters.Identity = "7giga7test7";
        myUrlParameters.Stage = "1337";
        myUrlParameters.Tags = new[] { "testbug", "gigatest" };
        myUrlParameters.Type = 0;
  #endregion
```

Right now, I want to generate an url based on this data. What function should I invoke to do so?

**Comment by dgilling** [comment]
This is how we use it in production, in our example this is a referral welcome offer/get X Dollars from friend invite program.

We first declare a DTO Model with the custom data, but you can use UrlDataParameters directly if no custom data fields as in your case.

```
public class BranchWelcomeReferral : UrlDataParameters
{
    public string PromoId { get; set; }

    public string SenderUserId { get; set; }

    public string SenderName { get; set; }

    public string SenderProfileUrl { get; set; }
}
```

Then we initialize the Lib:

```
        var config = new BranchNet.Config.BranchConfig
        {
            BranchKey    = “My Branch Key",
            BranchSecret = “My Branch Secret"
        };
        branchClient = new BranchClient(config);
```

And in our Create URL Function:

```
        var payload = new UrlParameters<BranchWelcomeReferral>()
        {
            Data        = referralData,
            Type        = BranchNet.Constants.UrlType.UNLIMITED_USE,
            Identity    = userId,
            Tags        = “My Tags",
            Campaign    = “My Campaign",
            Feature     = BranchConstants.FEATURE_TAG_REFERRAL
        };

        var syncResponse = _branchClient.CreateUrl<UrlParameters<BranchWelcomeReferral>, BranchWelcomeReferral>(payload);
        return syncResponse.Result.Url;
```

So there are two objects to note: the actual UrlParameters and the UrlDataParameters which contain the custom payload.

In your case:

The Data Objects looks correct, you would just need to call:

```
        var syncResponse = _branchClient.CreateUrl<UrlParameters<UrlDataParameters>, UrlDataParameters>(myUrlParameters);
        return syncResponse.Result.Url;
```

**Comment by Malavos** [comment]
Hey @dgilling  thanks for the tip!

:+1:  

That looks good. Now, if you don't mind, I've got another question!
I've added credits to a identity as in so:

```
        CreditParameters creditParams = new CreditParameters("gigatestbug", 100);
```

And I try to get the credits from this user, it comes correctly: 

```
        var aux = client.GetCreditCount("gigatestbug");
```

It returns 100 correctly.
The problem is, in my dashboard, I cannot find that Identity. Do I need to create it, somehow, beforehand? How should I do so?

Thanks again! After that, can I help with some documentation on the Readme.md?

**Comment by dgilling** [comment]
The branch dashboard is still a little lacking. I think you can see credits applied under the Liveview

![image](https://cloud.githubusercontent.com/assets/9476006/17607245/6b736112-5fd9-11e6-9ca0-5f671e792351.png)

**Comment by Malavos** [comment]
@dgilling  yes, I tried checking there, but after adding it as my aux, it does not shows up there as "gigatestbug", the test identity I am currently using.

How can I identify this?

Anyway, I e-mailed branch.io as well!

Thanks a ton!

**Comment by Malavos** [comment]
Hey @dgilling , It was confirmed as a bug in branch.io dashboard.

We have switched it over.

Thanks you very much for your help anyway! :v:
